In [1]:
#1. Uyarıları kapatınız




In [2]:
#2.   0 ile 20 arasında rasgele sayılar alan 10 satır ve 2 sutundan oluşan bir 
# matris oluşturun

import numpy as np
   
array = np.random.randint(21, size=(10, 2))

#sayıları sınırlandırma kodu 5 ile 30 arasında sınırlandır
#array = np.clip(array, 5, 30)
print(array)


[[16 17]
 [ 1 10]
 [ 5  6]
 [ 4 13]
 [14 13]
 [ 1  1]
 [18  6]
 [ 2 10]
 [ 3  9]
 [16 12]]


In [3]:
#3.  Aşağıdaki komut sonrası oluşturulan ikiboyutlu matrisi 2 ve 4 nolu 
# sutunlardan ayrıştırarak 3 adet a, b ve c martislerine dönüştürün. 
import numpy as np
m = np.arange(30).reshape(5,6)
print(m)
a = m[:,:2].reshape(-1, 2)
b = m[:, 2:4].reshape(-1,2)
c = m[:,4:6].reshape(-1,2)

print("Matris a:")
print(a)

print("\nMatris b:")
print(b)

print("\nMatris c:")
print(c)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Matris a:
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]]

Matris b:
[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]
 [26 27]]

Matris c:
[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]]


In [4]:
#4.   Aşağıdaki komut sonrası oluşturulan ikiboyutlu matrisi 3 nolu satırdan 
# ayrıştırarak 2 adet a ve b martislerine dönüştürün
import numpy as np
m = np.arange(30).reshape(5,6)
import numpy as np
m = np.arange(30).reshape(5,6)
print(m)
a= m[0:2,:].reshape(2,-1)
print("\n")
print(a)
b = m[2:,:].reshape(3,-1)
print("\n")
print(b)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [5]:
#5.  Aşağıdaki komutlar sonrası oluşturulan a matrisini colon adları “sutun1”,
#  ”sutun2” olan dataframe'e dönüştürün.
import numpy as np
import pandas as pd

a=np.random.randint(0,20,(10,2))

a=np.random.randint(0,20,(10,2))
print(a)

x=pd.DataFrame(data=a,index=range(10),columns=["sutun1","sutun2"])
print(x)





[[ 4 19]
 [ 5 18]
 [ 2 18]
 [10  8]
 [12  1]
 [18 16]
 [17 11]
 [18  8]
 [11 14]
 [18 13]]
   sutun1  sutun2
0       4      19
1       5      18
2       2      18
3      10       8
4      12       1
5      18      16
6      17      11
7      18       8
8      11      14
9      18      13


In [6]:
#6. Önceki soruda oluşturulan dataframe’in index’lerini “i1”,”i2”,...,”i10” 
# olarak değiştiriniz
import pandas as pd
import numpy as np
x=pd.DataFrame(data=a,index=range(1,11),columns=["sutun1","sutun2"])
x.index=(f"i{index}" for index in range(1,11))
print(x)



     sutun1  sutun2
i1        4      19
i2        5      18
i3        2      18
i4       10       8
i5       12       1
i6       18      16
i7       17      11
i8       18       8
i9       11      14
i10      18      13


In [7]:
#7. Aşağıdaki sözlük yapısındaki 99 değerini 100 olarak değiştirmek için 
# komutu yazınız. 
sozluk = {"A" : {"D":[1,2]},  "B" : {"E": [3,99,5]},  "C" : ["F",6]}

sozluk["B"]["E"][1] = 100
print(sozluk)


{'A': {'D': [1, 2]}, 'B': {'E': [3, 100, 5]}, 'C': ['F', 6]}


In [8]:
#8. 1 ile 10 dahil ardışık tam sayılardan oluşan bir numpy dizisi oluşturun 
# ve bu diziyi 5 satır ve 2 sutundan oluşan bir matrise dönüştürün. 
import numpy as np
m = np.arange(1,11).reshape(5,2)
print(m)





[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [9]:
#9. Önceki soruda oluşturulan matrisi bir dataframe!e dönüştürün ve bu dataframe’e 
# ilk 2 sutun toplamlarından oluşan yeni bir “toplam” adlı sutun ekleyin. 
import numpy as np
import pandas as pd
m = np.arange(1,11).reshape(5,2)
df=pd.DataFrame(data=m,index=range(5))

df['Toplam'] = df[0] + df[1]
print(df)


   0   1  Toplam
0  1   2       3
1  3   4       7
2  5   6      11
3  7   8      15
4  9  10      19


In [10]:
#10. İki adet a = [1,2,3,4] ve b = [5,6,7,8] numpy dizisi oluşturun ve bu dizileri 
# içeren yeni bir 2 boyutlu c numpy matrisi oluşturun.
import numpy as np
m = np.arange(1,5).reshape(1,4)
n=np.arange(5,9).reshape(1,4)
c = np.array([m, n])

print(c)


[[[1 2 3 4]]

 [[5 6 7 8]]]


In [11]:
#11. 10 ile 20 arasında 10 adet rasgele tam sayıdan oluşan bir numpy dizisi oluşturun 
# ve bu dizinin ortalamasından büyük olan sayılardan oluşan listeyi yazdırınız. 

import numpy as np

numpy_dizi = np.random.randint(10, 21, 10)

ortalama = np.mean(numpy_dizi)
buyuk_sayilar = [sayi for sayi in numpy_dizi if sayi > ortalama]

print("Oluşturulan Numpy Dizisi:", numpy_dizi)
print("Dizinin Ortalaması:", ortalama)
print("Ortalamadan Büyük Sayılar:", buyuk_sayilar)




Oluşturulan Numpy Dizisi: [14 12 16 17 20 10 13 18 11 18]
Dizinin Ortalaması: 14.9
Ortalamadan Büyük Sayılar: [16, 17, 20, 18, 18]


In [12]:
#12. -50 ile 50 arası rasgele sayılardan oluşan 10 elemanlık bir numpy dizisi oluşturun. 
# Bu elemanların Z-score normalleştirilmiş değerlerinden oluşan b dizisi oluşturunuz
import numpy as np
from scipy.stats import zscore

array = np.random.randint(-50,51, 10)
b = zscore(array)
print(array)
print(b)


[ 27   7  33 -17 -29 -39 -21 -40  26  38]
[ 0.96866519  0.28890014  1.1725947  -0.52681791 -0.93467694 -1.27455946
 -0.66277092 -1.30854771  0.93467694  1.34253597]


In [13]:
#13. Aşağıdaki şekilde bir dataframe oluşturulmuştur. Bu dataframe’in gruplara göre 
# veri ortalamalarını yansıtan tabloyu yazdıran komutu yazınız.
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'deger':[1,2,3,4,5,6],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri','deger'])


mean = df.groupby('gruplar')['veri'].mean()
print(mean)



gruplar
A    16.5
B    27.0
C    53.5
Name: veri, dtype: float64


In [14]:
#14. “;” karakterleri ile ayrılmış veriler içeren dış kaynaklı “veri.csv” dosyasını 
# bir dataframe’e okumak için komutu yazınız

#import pandas as pd
#df = pd.read_csv('veri.csv', sep=';')



In [15]:
#15. Parametre olarak aldığı bir kelimeyi tümüyle büyük karakterlere dönüştürerek 
# geri döndüren "funk" adlı bir fonksiyonun tanımını yazınız. 

def funk (word):
    turkce_ceviri_tablosu = str.maketrans("abcçdefgğhıijklmnoöprsştuüvyz", "ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ")
    return word.translate(turkce_ceviri_tablosu).upper()

a=funk("ali")
print(a)





ALİ


In [16]:
#16. Python’da “seaborn” kütüphanesinden “mpg.csv” veri setini indiriniz, 
# veri seti bilgilerini yazdırınız (info),
# veri setinin ilk 10 satrını ekrana yazdırınız

import pandas as pd

df = pd.read_csv('/kaggle/input/mpglastdata/mpg_veri.csv')

print(df.info)
print(df.head(10))




<bound method DataFrame.info of       mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu

In [17]:
#17. veri setinin uygun atributlraına göre ortalama, varyans, min, max, vs. 
# değerleri yazdırınız,
import pandas as pd

a = df.describe()
a.loc['variance'] = a.loc['std'] ** 2
#standart sapmanın karesi varyanstır ve onu describea ekledim

print(a)




                 mpg   cylinders  displacement   horsepower         weight  \
count     398.000000  398.000000    398.000000   392.000000     398.000000   
mean       23.514573    5.454774    193.425879   104.469388    2970.424623   
std         7.815984    1.701004    104.269838    38.491160     846.841774   
min         9.000000    3.000000     68.000000    46.000000    1613.000000   
25%        17.500000    4.000000    104.250000    75.000000    2223.750000   
50%        23.000000    4.000000    148.500000    93.500000    2803.500000   
75%        29.000000    8.000000    262.000000   126.000000    3608.000000   
max        46.600000    8.000000    455.000000   230.000000    5140.000000   
variance   61.089611    2.893415  10872.199152  1481.569393  717140.990526   

          acceleration  model_year  
count       398.000000  398.000000  
mean         15.568090   76.010050  
std           2.757689    3.697627  
min           8.000000   70.000000  
25%          13.825000   73.000000

In [18]:
#18. “horsepower” ve “weight” atributları için, “origin” kırılımına (hue) 
# göre “scatter plot” grafiğini oluşturunuz
import matplotlib.pyplot as plt
import seaborn as sns

sns.scatterplot(x='horsepower', y='weight', hue='origin', data=df)
plt.show()



In [19]:
#19. “mpg” ve “acceleration” değişkenleri arasında Kendall 
# korelasyon katsayısını hesaplamalı ve yazdırmalı.
from scipy.stats import kendalltau

kendall_corr, p_value = kendalltau(df['mpg'], df['acceleration'])
print(f"Kendall Korelasyon Katsayısı: {kendall_corr}")


Kendall Korelasyon Katsayısı: 0.30109590846759365


In [20]:
#20. “horsepower”, “acceleration” ve “weight” değişkenlerine göre 
# “mpg” değerinin tahmini için 
# LinearRegression() modeli oluşturunuz
# Modelin intercept ve katsayılarını yazdırınız
# NOT: kayıp veriler olabilir. Gerekirse kayıp verileri siliniz.
from sklearn.linear_model import LinearRegression


df = df.dropna(subset=['horsepower', 'acceleration', 'weight', 'mpg'])

X = df[['horsepower', 'acceleration', 'weight']]
y = df['mpg']
model = LinearRegression()

#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model.fit(X, y)
print(f"Intercept (Kesişim): {model.intercept_}")
print("Katsayılar:")
for feature, coefficient in zip(X.columns, model.coef_):
    print(f"{feature}: {coefficient}")

#implace true yapmadım





Intercept (Kesişim): 45.67829287695591
Katsayılar:
horsepower: -0.04749561533211888
acceleration: -0.002065657852236782
weight: -0.005789402592258984


In [21]:
#21. Oluşturulan modelin R-squared değerini yazdırınız
from sklearn.metrics import r2_score

r_squared = r2_score(y, model.predict(X))

# R-squared değerini yazdırın
print(f"R-squared değeri: {r_squared}")






R-squared değeri: 0.7063754859981903


In [22]:
#22. horsepower = 130, acceleration=13, weight=3500 olan bir 
# otomobilin “mpg” değerini tahmin ediniz.
from sklearn.linear_model import LinearRegression

exm = model.predict([[130, 13, 3500]])

# Tahmin edilen "mpg" değerini yazdır
print(f"Tahmin edilen MPG değeri: {exm[0]:.2f}")




Tahmin edilen MPG değeri: 19.21


/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [23]:
#23. “mpg.csv” veri setini, “mpg”, “displacement”,”horsepower”,”weight” 
#ve “acceleration” değişkenlerine göre
#“origin” değerinin tahmini için %20 test,%80 eğitim oranında ayrıştırınız. Eğitim setini kullanarak
#RandomForest sınıflandırma modeli oluşturunuz
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier



df.dropna(subset=['horsepower', 'acceleration', 'weight', 'mpg','displacement'])

X = df[["mpg", "displacement", "horsepower", "weight", "acceleration"]]
y = df["origin"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

In [24]:
#24. Oluşturulan modelin test seti üzerinde doğruluk (accuracy) skorunu hesaplayınız,
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier


accuracy = accuracy_score(y_test, y_pred)

# Modelin doğruluk skorunu yazdır
print(f"Modelin Doğruluk Skoru: {accuracy:.2f}")






Modelin Doğruluk Skoru: 0.80


In [25]:
#25.Değişkenlerin önem derecelerini (Importance) yazdırınız.
from sklearn.ensemble import RandomForestClassifier

importance = rf_model.feature_importances_

feature_importance = dict(zip(X.columns, importance))

for feature, importance in feature_importance.items():
    print(f"{feature}: {importance}")


mpg: 0.16510823507284783
displacement: 0.3407463630116737
horsepower: 0.16753911675494432
weight: 0.2065433846316926
acceleration: 0.1200629005288415
